apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-octave 
  labels:
    name: jupyter-octave 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jupyter-octave 
  template:
    metadata:
      labels:
        name: jupyter-octave 
    spec:
      volumes:
      - hostPath:
          path: /volumes/jupyter-home/octave
        name: home 
      containers:
      - name: jupyter-octave 
        image: jupyter/octave-notebook
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8888 
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - mountPath: /home/jovyan
          name: home 
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-octave 
  labels:
    name: jupyter-octave 
spec:
  ports:
  - name: webport 
    protocol: "TCP"
    port: 8888 
    targetPort: 8888 
    nodePort: 8888 
  selector:
    name: jupyter-octave 
  type: NodePort

